### ISSUE TITLE
bowl.stop() requires full restart to play again

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#192] opened 2023-03-19 04:16 UTC
Once bowl.stop() is used, nothing will play again until a full restart of Sardine via exit() and fishery command is given. 

bowl.pause() and bowl.resume() work as expected. 

bowl.stop() will stop all running functions as expected. 

But now no commands will restart play:
- bowl.start() # does nothing
- bowl.resume() # does nothing
- Pa >> d('bd') #  will start swimming, but with no sound

This is not a high priority, but until it is fixed -- bowl.stop() should not be used and a known issue noted in the docs.

**Comment by Bubobubobubobubo** [comment] 2023-03-19 08:51
What clock are you using?

**Comment by HighHarmonics2** [comment] 2023-03-19 23:43
"link_clock": false,

**Comment by Bubobubobubobubo** [comment] 2023-03-19 23:58
Unfortunately, I can't really reproduce on my computer (MacOS Ventura). Here is a log from an interactive `fishery` session:
```python
>>> bowl
<FishBowl playing clock=<InternalClock running time=1.8 tempo=120 beats_per_bar=4>>
>>> bowl.stop()
True
>>> bowl
<FishBowl stopped clock=<InternalClock stopped time=4.9 tempo=120 beats_per_bar=4>>
>>> bowl.start()
True
>>> bowl
<FishBowl playing clock=<InternalClock running time=6.2 tempo=120 beats_per_bar=4>>
>>> bowl
<FishBowl playing clock=<InternalClock running time=7.0 tempo=120 beats_per_bar=4>>
>>>
```

**Comment by Bubobubobubobubo** [comment] 2023-04-10 20:43
Closing because I am unable to reproduce.

**Closed by Bubobubobubobubo** 2023-04-10 20:43 UTC
Labels: bug, can't reproduce
