### ISSUE TITLE
Surprising behavior of p

### ISSUE THREAD

**Issue by loig** [Bubobubobubobubo/sardine#256] opened 2024-06-07 12:25 UTC
When I evaluate something like that:

`Pa * d('bd cp', p='1 2')`

I would expect to hear something similar than when evaluating that:

`Pb * d('bd cp .')`

However I get something similar than when evaluating that:

`Pb * d('bd . cp')`

Am I misunderstanding something or is it a bug?

**Comment by Bubobubobubobubo** [comment] 2024-06-07 13:01
Hi, indeed this is quite surprising. I already saw that bug on some rare edge cases in the past but it always appeared on complex patterns. This is definitely not the intended behavior. It looks like `p` is somehow shifted now.. The player mechanism is entirely defined in [a single file](https://github.com/Bubobubobubobubo/sardine/blob/main/sardine_core/handlers/player.py). Hopefully it should not be too hard to isolate and fix.

**Comment by Bubobubobubobubo** [comment] 2024-06-15 22:58
This is now fixed on the `better-quant` branch that will be merged with `main` soon.

**Closed by Bubobubobubobubo** 2024-06-15 22:58 UTC
